---
- name: Deploy Spring Boot Realtime Chat App
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Clone Git repo
      git:
        repo: https://github.com/srinathk442/Real-time-Chat-Application.git
        dest: /opt/realtime-chat
        force: yes

    - name: Build with Maven
      shell: mvn clean install -DskipTests
      args:
        chdir: /opt/realtime-chat

    - name: Build Docker image
      shell: docker build -t realtime-chat-app .
      args:
        chdir: /opt/realtime-chat

    - name: Stop existing container (if running)
      shell: docker stop chat-app || true

    - name: Remove existing container (if exists)
      shell: docker rm chat-app || true

    - name: Run Docker container
      shell: docker run -d -p 8082:8080 --name chat-app realtime-chat-app
