---
- name: Deploy Spring Boot Realtime Chat App
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Stop existing container (if running)
      shell: docker stop chat-app || true

    - name: Remove existing container (if exists)
      shell: docker rm chat-app || true

    - name: Run Docker container
      shell: docker run -d -p 8082:8080 --name chat-app realtime-chat-app
